name: aether_core
description: Aether Core
version: 0.7.0
homepage: https://github.com/jasonlaw/aether_core.git

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # https://pub.dev/packages/get 
  get: ^4.6.5

  # https://pub.dev/packages/hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^3.0.3

  # https://pub.dev/packages/package_info_plus 
  package_info_plus: ^3.0.3
  
  # https://pub.dev/packages/url_launcher 
  url_launcher: ^6.1.10

  # https://pub.dev/packages/flutter_easyloading 
  flutter_easyloading: ^3.0.5

  # https://pub.flutter-io.cn/packages/version
  version: ^3.0.2
  
  # https://pub.dev/packages/crypto
  crypto: ^3.0.2

  # https://pub.dev/packages/cross_file
  cross_file: ^0.3.3+4

  # https://pub.dev/packages/money2
  # money2: ^3.1.2

  # https://pub.dev/packages/dio
  # https://github.com/flutterchina/cookie_jar
  # https://pub.dev/packages/path_provider
  dio: ^5.0.1
  # dio_cookie_manager: #^2.1.2
  #   path: ../cookie_manager
  cookie_jar: ^3.0.1
  path_provider: ^2.0.13
  # dio_logger: ^4.0.8+8
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # https://pub.dev/packages/flutter_lints
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.  
  flutter_lints: ^2.0.1


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/
  #   - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
